display_name: BiteClash

icon: ./assets/images/icon.png

supported_mime_type:
  - x-scheme-handler/clash
  - x-scheme-handler/clashmeta
  - x-scheme-handler/biteclash
  - x-scheme-handler/flclash

keywords:
  - BiteClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: BiteClash

categories:
  - Network

startup_notify: true

include: []